# 异常处理

## 网络请求的异常处理 

网络请求的异常将由 `@/utils/request` 函数自动处理。

`@/utils/request/error-handle` 会对捕获的错误进行消息提示。

`networkErrorHandler` 函数主要提示 **网络层** 错误；

其包含通用状态码的映射关系：

```js
const codeMessage = {
    200: '服务器成功返回请求的数据。',
    201: '新建或修改数据成功。',
    202: '一个请求已经进入后台排队（异步任务）。',
    204: '删除数据成功。',
    400: '发出的请求有错误，服务器没有进行新建或修改数据的操作。',
    401: '用户没有权限（令牌、用户名、密码错误）。',
    403: '用户得到授权，但是访问是被禁止的。',
    404: '发出的请求针对的是不存在的记录，服务器没有进行操作。',
    406: '请求的格式不可得。',
    410: '请求的资源被永久删除，且不会再得到的。',
    422: '当创建一个对象时，发生一个验证错误。',
    500: '服务器发生错误，请检查服务器。',
    502: '网关错误。',
    503: '服务不可用，服务器暂时过载或维护。',
    504: '网关超时。'
};
```

`businessErrorHandler` 函数主要提示 **业务层（服务端逻辑）** 错误，针对接口返回没有包含 `code` 的请求进行统一处理；

- 正常的接口返回格式：

```json 
{
    code: number,
    data: any
}
```

- 异常的接口返回格式：

```json 
{
    message: string 
}
```

## 代码层的异常处理

建议使用 `rxjs` 接管系统 UI 事件等行为，除此以外，可使用 `try/catch` 进行异常捕获。

